### ISSUE TITLE
Error: npm command is missing

### ISSUE THREAD

**Issue by jasonmacdonald** [willdurand/puppet-nodejs#154] opened 2016-06-08 13:22 UTC
I see this issue has come up before, but I can't for the life of me figure out why it's happening to me here. I'm using Vagrant/virtualbox with the bento/centos6.7 box, and doing the simplest install, it fails with "Error: npm command is missing". Logging into the box shows npm is installed and available globally.

My simple puppet file

```
Exec { path => ['/bin/', '/sbin/' , '/usr/bin/', '/usr/sbin/', '/usr/local/sbin/', '/usr/local/bin/', '/usr/local/node/node-default/bin/']}

class { 'nodejs':
    version => 'stable',
    make_install => false
  }

  package { 'express':
    provider => 'npm',
    require  => Class['nodejs']
  }
```

This is literally all I have. Funny thing is, if I switch to the ubuntu/trusty64 box it works. Is this somehow specific to Centos-6.7?

Here is the error

```
==> web: Info: Applying configuration version '1465390748'
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Package[git]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[nodejs-install-dir]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[nodejs-symlink-bin-with-version-v6.2.1]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Package[semver]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Nodejs::Install::Download[nodejs-download-v6.2.1]/Exec[nodejs-wget-download-http://nodejs.org/dist/v6.2.1/node-v6.2.1-linux-x64.tar.gz-/usr/local/node/node-v6.2.1-linux-x64.tar.gz]/returns: executed successfully
==> web: Notice: /File[nodejs-check-tar-v6.2.1]/seluser: seluser changed 'unconfined_u' to 'system_u'
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[/usr/local/node/node-v6.2.1]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Exec[nodejs-unpack-v6.2.1]/returns: executed successfully
==> web: Notice: /Stage[main]/Nodejs/File[/usr/local/node/node-default]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/File[/usr/local/bin/node]/ensure: created
==> web: Notice: /Stage[main]/Nodejs/File[/etc/profile.d/nodejs.sh]/ensure: defined content as '{md5}8597b319c5c64b65e65b3e398d130af8'
==> web: Notice: /Stage[main]/Nodejs/File[/usr/local/bin/npm]/ensure: created
==> web: Error: Command npm is missing
==> web: Error: /Stage[main]/Profile::Node/Package[express]/ensure: change from absent to present failed: Command npm is missing
```

Edit: I should also note that rerunning vagrant provision again after the initial "up" call does find npm and installs express. It's only the first vagrant up that fails.

**Comment by jasonmacdonald** [comment] 2016-06-08 13:56
For some added info, if I add an exec call in between the nodejs and the package, the exec call to "npm install" works, but the package call still fails.

```
  class { 'nodejs':
    version => 'stable',
    make_install => false
  }

  exec { "pm2":
    command => "npm install -g pm2",
    logoutput => true,
    loglevel => info,
    require => Class['nodejs']
  }

  package { 'express':
    provider => 'npm',
    require  => Exec['pm2']
  }
````

Here the pm2 global install works, showing npm is installed, but the call to package to install express fails as before.

**Comment by Ma27** [comment] 2016-06-08 15:27
Using Ubuntu 14.04 with Vagrant 1.7 and Puppet 4.3.4 inside Vagrant your code works:

```
==> default: Info: Applying configuration version '1465399302'
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Package[git]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Package[ruby]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Package[semver]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[nodejs-install-dir]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[/usr/local/node/node-v6.2.1]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[nodejs-symlink-bin-with-version-v6.2.1]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/File[npm-symlink-bin-with-version-v6.2.1]/ensure: defined content as '{md5}318c0d7826b14506ba6b4c52b29fdceb'
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Nodejs::Install::Download[nodejs-download-v6.2.1]/Exec[nodejs-wget-download-http://nodejs.org/dist/v6.2.1/node-v6.2.1-linux-x64.tar.gz-/usr/local/node/node-v6.2.1-linux-x64.tar.gz]/returns: executed successfully
==> default: Notice: /Stage[main]/Nodejs/Nodejs::Install[nodejs-stable]/Exec[nodejs-unpack-v6.2.1]/returns: executed successfully
==> default: Notice: /Stage[main]/Nodejs/File[/usr/local/node/node-default]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/File[/usr/local/bin/node]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/File[/usr/local/bin/npm]/ensure: created
==> default: Notice: /Stage[main]/Nodejs/File[/etc/profile.d/nodejs.sh]/ensure: defined content as '{md5}8597b319c5c64b65e65b3e398d130af8'
==> default: Notice: /Stage[main]/Main/Package[express]/ensure: created
==> default: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
```

The reason why the manual ``npm install`` works is due to the fact that ``Exec { path => 'foo' }`` modifies the path for every ``exec`` resource, but not for the underlying shell stuff.

As you didn't modify the ``$target_dir`` parameter, I assume that everything will be installed into ``/usr/local/bin``?
I think that your problem is that the underlying shell doesn't have ``/usr/local/bin`` configured in ``$PATH``?
If so, the simplest solution would be to change the ``$target_dir`` parameter.

**Comment by jasonmacdonald** [comment] 2016-06-08 16:44
Thanks Ma27. Like I said, this only seems to happen with CentOS and not Ubuntu. 

Correct me if I'm wrong, but doesn't Vagrant run puppet as root? Checking root $PATH I see

```
/usr/local/node/node-default/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```
so it's in the PATH.

I'll admit, I'm a UI developer. Trying to dip toes into system admin (dev-ops) stuff here, I'm struggling a bit. :(

**Comment by Ma27** [comment] 2016-06-08 19:14
ok, that's odd.
In the next time I'll try to do it again with a ``bento/centos`` box (btw which one do you use exactly?) and then we'll see...

**Comment by jasonmacdonald** [comment] 2016-06-08 19:33
I'm using bento/centos-6.7.

**Comment by Ma27** [comment] 2016-06-08 19:58
maybe this is the cause for everything? (http://blogs.perl.org/users/vyacheslav_matjukhin/2013/05/usrlocalbin-rant.html)

Please try changing the ``$target_dir`` parameter to sth. else and opost the command output here.

**Comment by jasonmacdonald** [comment] 2016-06-09 11:28
@Ma27 Yup, setting `$target_dir` to `/bin/` does resolve the issue. Thanks! It might be worth updating the docs to mention this so others don't stumble on the same thing. Thanks again, @Ma27 !

**Comment by Ma27** [comment] 2016-06-09 13:02
ok, good if it works for you.
You're right, the documentation is a bit messy right now, I think in 2.0 it should contain more information about such edge cases.

**Comment by Ma27** [comment] 2016-07-15 07:52
@jasonmacdonald reopening. I think we should make the `::nodejs::params` more generic so it provides `/usr/local/bin` in case of Debian, but another directory for RedHat/CentOS by relying on the `::osfamily` fact.

**Comment by Ma27** [comment] 2016-07-15 09:42
such stuff (https://github.com/willdurand/puppet-nodejs/blob/master/manifests/install.pp#L164-L167) might be written in order to get the appropriate target path...

**Comment by LeeGDavis** [comment] 2017-02-17 18:41
I believe I'm running into this same issue, however node and npm appear to be installed and available in the correct locations.  When the provider 'npm' is used it throws this error, however subsequently ssh onto that box and looking for node and npm they are available and on the path.

puppet-nodejs 1.9.6
vagrant 1.8.6
rhel7.2

```
class { 'nodejs':
  version => 'v6.9.5',
  make_install => false,
}

package { 'coffee-script':
  provider => npm,
  install_options => ['-g'],
  require => Class['nodejs']
}
```
```
Error: Command npm is missing
Error: /Stage[main]/Express::Node/Package[coffee-script]/ensure: change from absent to present failed: Command npm is missing
```

However all seems to be well with the actual install
```
$ which npm node
/usr/local/node/node-default/bin/npm
/usr/local/node/node-default/bin/node

$ ll /usr/local/bin/node
lrwxrwxrwx. 1 root root 37 Feb 17 12:10 /usr/local/bin/node -> /usr/local/node/node-default/bin/node
$ ll /usr/local/bin/npm
lrwxrwxrwx. 1 root root 36 Feb 17 12:10 /usr/local/bin/npm -> /usr/local/node/node-default/bin/npm
```

I have tried manipulating `target_dir` without success too.  I am not sure what to pursue next to address this issue.

**Comment by Ma27** [comment] 2017-02-17 18:47
Is it possible that `/usr/local/bin` is not in your `$PATH` (at least not of the `root` user maybe?)?
And which `target_dir` did you choose?

However, I'll try to have a look at this on the weekend

**Comment by LeeGDavis** [comment] 2017-02-17 18:55
Thanks @Ma27!

Root's path appears correct too:
```
echo $PATH
/usr/local/node/node-default/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

In regard to `target_dir` I have tried the following

- `target_dir => '/usr/local/bin'`
- `target_dir => '/usr/local/node/node-default/bin'`
- `target_dir => '/bin'` (Even though npm and node are not available here)

**Comment by LeeGDavis** [comment] 2017-02-20 18:43
To provide some more context, if I remove the provider usage of NPM and have an require call on nodejs, I receive the following error:
```
Error: /usr/bin/env: node: No such file or directory
...
Error: /Stage[main]/Express::Node/Exec[npm_registry]/returns: change from notrun to 0 failed: /usr/bin/env: node: No such file or directory
```

Which appears to be failing on the following:
```
exec { 'npm_registry':
  command => "/usr/local/node/node-default/bin/npm config set registry $npm_registry",
  user => root,
  require => Class['nodejs'],
}
```

**Comment by Ma27** [comment] 2017-02-21 17:23
@LeeGDavis are you sure that the path that is available during your `ssh` session is the same as during the puppet run? You mentioned that the executables are available during a `ssh` session, but not during the puppet run. Most of the time the `path` is configured using an `Exec { path => "..." }` construct at the highest scope for all sub-scopes, maybe this fixes the issue (in that case the documentation lacks enough information as well which needs to be fixed before releasing final `2.0`).

If this doesn't help it would be nice if you could paste (if possible) the entire output of the puppet run (it may contain some more information that could be helpful for us) and post the version of `puppet` you're using.

**Comment by LeeGDavis** [comment] 2017-02-22 00:30
@Ma27 That is a good question. You will have to excuse my ignorance with puppet, but what steps would one take to determine the `path` during the puppet run and have it logged to the console?

I'll also look into getting a copy of those logs if I can release them.

**Comment by Ma27** [comment] 2017-02-22 05:55
https://www.puppetcookbook.com/posts/set-global-exec-path.html

Just do this at the top of your manifest and use the `path` that is used during the `ssh` session.

**Comment by LeeGDavis** [comment] 2017-02-23 21:39
@Ma27 We tried the global exec path and same error presents itself.  I'm still convinced that whatever puppet is running as (assumed root) does not have visibility into what appears to be a successful installation.

**Comment by LeeGDavis** [comment] 2017-02-23 23:11
Also second time around re-provisioning, this works fine.  So it certainly appears to be a path issue.

**Comment by LeeGDavis** [comment] 2017-02-24 19:08
@Ma27 It appeared the problem was an older version of puppet (3.8.x) and the path.  Altering the global path never seemed to resolve the issue for us, however under puppet 4.x manipulating the `target_dir` to `/bin` or `/usr/bin` resolves the issue.  Thanks again for your help with this!

**Comment by Ma27** [comment] 2017-02-24 20:51
great if it works for you :-)

**Comment by Ma27** [comment] 2017-03-24 20:28
closing for now. The entire behavior is a little bit odd, so if someone else faces this issue, please where we can talk about it and I'll do my best to investigate :-)

I'll try to improve the docs a little bit before releasing 2.0.0-final, so this should cause less bugs.

**Closed by Ma27** 2017-03-24 20:28 UTC
Labels: bug, support
