### ISSUE TITLE
Wrong NodeJS version installed

### ISSUE THREAD

**Issue by perry-mitchell** [willdurand/puppet-nodejs#170] opened 2017-02-25 15:57 UTC
### Description

The latest version is installed, no matter what I set for "version".

### Steps to reproduce

Setting either of the following cause 7.6 to be installed:

```
class { '::nodejs':
    version => '6.10',
}
```

```
class { 'nodejs':
    version => 'v6.10.0',
}
```

### Expected behavior

Version 6.10.0 should be installed.

### Further details

The virtual machine I'm provisioning is Ubuntu 16.04 in virtualbox. I'm using puppet 3.8.

I get crazy-long install output:
![image](https://cloud.githubusercontent.com/assets/3869469/23332517/b140c6b2-fb83-11e6-99fb-135367fa3378.png)

And then catastrophic failure:
![image](https://cloud.githubusercontent.com/assets/3869469/23332520/ce3fb12e-fb83-11e6-90cc-4af50af282a1.png)

**Comment by Ma27** [comment] 2017-02-25 16:56
Thanks for submitting an issue.
Which version of this module do you use?

**Comment by perry-mitchell** [comment] 2017-02-25 17:01
I'm not sure.. I used the example from the readme which doesn't specify a version..

How do I check?

**Comment by Ma27** [comment] 2017-02-25 17:08
how did you install this module? Cloned master or some of the 1.9 versions? As noted in the README the current obe on master is for the 2.0 versions...

**Comment by Ma27** [comment] 2017-03-24 20:22
@perry-mitchell does this issue still exist? If yes, how can I help?

**Comment by perry-mitchell** [comment] 2017-03-24 22:48
> how did you install this module? Cloned master or some of the 1.9 versions? As noted in the README the current obe on master is for the 2.0 versions...

I installed it by simply running `puppet module install willdurand/nodejs` as in the readme.

> does this issue still exist?

I can confirm that it still exists. I'm installing it via puppet 3.8 for Ubuntu 16.04 - seems to be version 1.9.6:

![image](https://cloud.githubusercontent.com/assets/3869469/24316113/38bac964-10f4-11e7-8a34-1f043bd45ee0.png)

It still fails after a huge amount of output:

![image](https://cloud.githubusercontent.com/assets/3869469/24316174/a7e4586e-10f4-11e7-8f50-29b62b8725ba.png)

![image](https://cloud.githubusercontent.com/assets/3869469/24316136/68b6ecb0-10f4-11e7-84f0-51a275c1e8d4.png)

And then eventually ends in failure:
![image](https://cloud.githubusercontent.com/assets/3869469/24316150/83536314-10f4-11e7-89c9-43d2720ff315.png)

This is a fresh install, and the only other software I'm installing is mysql and nginx.

**Comment by Ma27** [comment] 2017-03-25 07:55
seems to be caused by a compilation failure.

A possible workaround on 1.x would be to use `make_install => false` to download a precompiled package from `nodejs.org/dist`.

However I'll try to reproduce this in the next days...

**Comment by Ma27** [comment] 2018-04-14 09:50
please excuse the delay, I didn't have sufficient time to work on thisproject for quite some time now.

I just created a VM with `Vagrant 2.0` and `VirtualBox 5.2.8` on NixOS 18.03.
When provisioning the box with `Puppet 4` and `puppet-nodejs 1.9.6` with the following manifest everyting works fine and the proper version will be installed:

```puppet
exec { 'apt-get update': } ->
class { '::nodejs':
  version      => 'v6.10.0',
  make_install =>  true
}
```

I'm closing this for now as not reproducible, just feel free to ping me if there's anything I missed!

**Closed by Ma27** 2018-04-14 09:50 UTC
Labels: bug, feedback needed
