### ISSUE TITLE
Node is not available in npm preinstall

### ISSUE THREAD

**Issue by wwhurley** [willdurand/puppet-nodejs#108] opened 2015-12-17 14:37 UTC
On the first installation the command `node` is not available if called from an npm `preinstall` script. For example when attempting to install the SailsJS package globally using something like:

```
class { '::nodejs':
  version	 => 'v0.12.9',
  make_install => false,
}

package { ['bower', 'grunt-cli', 'sails']:
  ensure   => present,
  provider => 'npm',
  require  => Class['::nodejs']
}
```

It gives the following error the first time through
```
==> default: Error: Execution of '/usr/local/node/node-default/bin/npm install --global grunt-cli bower sails' returned 1: 
==> default: > sails@0.11.3 preinstall /usr/local/node/node-default/lib/node_modules/sails
==> default: > node ./lib/preinstall_npmcheck.js
==> default: 
==> default: sh: node: command not found
==> default: /usr/local/node/node-default/bin/grunt -> /usr/local/node/node-default/lib/node_modules/grunt-cli/bin/grunt
==> default: /usr/local/node/node-default/bin/bower -> /usr/local/node/node-default/lib/node_modules/bower/bin/bower
==> default: npm ERR! Linux 2.6.32-358.el6.x86_64
==> default: npm ERR! argv "/usr/local/node/node-default/bin/node" "/usr/local/node/node-default/bin/npm" "install" "--global" "grunt-cli" "bower" "sails"
==> default: npm ERR! node v0.12.9
==> default: npm ERR! npm  v2.14.9
==> default: npm ERR! file sh
==> default: npm ERR! code ELIFECYCLE
==> default: npm ERR! errno ENOENT
==> default: npm ERR! syscall spawn
==> default: 
==> default: npm ERR! sails@0.11.3 preinstall: `node ./lib/preinstall_npmcheck.js`
==> default: npm ERR! spawn ENOENT
==> default: npm ERR! 
==> default: npm ERR! Failed at the sails@0.11.3 preinstall script 'node ./lib/preinstall_npmcheck.js'
```

**Comment by Ma27** [comment] 2016-01-16 16:15
this is not a bug related to this module, but an issue with puppet.
Puppet does not provide a "proper" shell integration.

THis should be fixed when writing this at the top of your manifest

``` puppet
Exec {
    path => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
}
```

**Comment by willdurand** [comment] 2016-01-16 19:42
:+1:

**Closed by willdurand** 2016-01-16 19:42 UTC
