### ISSUE TITLE
Version lts, latest, major.x, major.minor won't install

### ISSUE THREAD

**Issue by cogliostro** [willdurand/puppet-nodejs#182] opened 2018-06-20 10:46 UTC
### Description

When I specify lts, latest, 8.x or 8.11 as version I get the following error. It works if i specify 8.11.3.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Network is unreachable - connect(2) at /etc/puppet/environments/reetablering_opl_kj/modules/nodejs/manifests/init.pp:61

### Expected behavior

As described in the documentation, I expect the installed package to be latest lts, latest, latest of major version 8 and latest of major/minor version 8.11.

### Further details

REHL 7.5
Puppet version 3.8.7
Facter version 2.4.6

**Comment by Ma27** [comment] 2018-06-20 12:32
I'm sorry that you're experiencing issues with this module!
Unfortunately I couldn't reproduce the issue locally when deploying into a Debian 8 and CentOS 7 box using Vagrant.

However I'm fairly certain that this isn't related to any OS or Puppet version, but much rather a networking issue. The versions will be detected using functions being evaluated on the Puppet master. However the actual downloads happen when applying the catalogue to the target system.

Can you checck if you can reach `nodejs.org` from your Puppet master?

**Comment by cogliostro** [comment] 2018-06-20 13:01
Ok. The puppetmaster is behind a whitelisting proxy. So that is probably the issue then. I'll see if I can get the people responsible for the proxy to whitelist nodejs.org.

**Comment by cogliostro** [comment] 2018-06-20 13:32
Looks like I have to turn this into a feature request. It shouldn't be hard to enable setting the proxy config from params in addition to env variables?

**Comment by Ma27** [comment] 2018-06-20 15:42
That's (more or less) what I expected.

The easiest workaround is still to pin your setup to a given version and bump manually though.
In case you need additional support for your issue or have an additional request regarding this issue feel free to ping me.
Unless I'd close this issue in the next days :)

**Comment by Ma27** [comment] 2018-06-21 10:33
closing now as this is clearly a networking issue. In case anyone requires additional support or wants to discuss some improvements feel free to open an issue or file a patch :)

**Closed by Ma27** 2018-06-21 10:33 UTC
Labels: bug
